In [57]:
!pip install kagglehub[pandas-datasets]

Collecting kagglehub[pandas-datasets]
  Using cached kagglehub-0.3.13-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: packaging in ./.venv/lib/python3.12/site-packages (from kagglehub[pandas-datasets]) (25.0)
Requirement already satisfied: pyyaml in ./.venv/lib/python3.12/site-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in ./.venv/lib/python3.12/site-packages (from kagglehub[pandas-datasets]) (2.32.5)
Requirement already satisfied: tqdm in ./.venv/lib/python3.12/site-packages (from kagglehub[pandas-datasets]) (4.67.1)
Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (from kagglehub[pandas-datasets]) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas->kagglehub[pandas-datasets]) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.12/site-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.12/site-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests->kagglehub[pandas-datasets]) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests->kagglehub[pandas-datasets]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.12/site-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.12/site-packages (from requests->kagglehub[pandas-datasets]) (2025.10.5)
Using cached kagglehub-0.3.13-py3-none-any.whl (68 kB)
Installing collected packages: kagglehub
Successfully installed kagglehub-0.3.13

In [58]:
# # pip install kagglehub[pandas-datasets]
import kagglehub
#this is working
path = kagglehub.dataset_download("computingvictor/transactions-fraud-datasets")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/computingvictor/transactions-fraud-datasets?dataset_version_number=1...

100%|██████████| 348M/348M [00:03<00:00, 103MB/s]

Extracting files...

Path to dataset files: /home/coder/.cache/kagglehub/datasets/computingvictor/transactions-fraud-datasets/versions/1

In [1]:
# start here

In [60]:
# Install dependencies as needed:

# from kagglehub import KaggleDatasetAdapter

# # Set the path to the file you'd like to load
# file_path = "/home/coder/data"
# kagglehub.login()
# # Load the latest version
# df = kagglehub.dataset_load(
#   KaggleDatasetAdapter.PANDAS,
#   "computingvictor/transactions-fraud-datasets",
#   file_path,
#   # Provide any additional arguments like 
#   # sql_query or pandas_kwargs. See the 
#   # documenation for more information:
#   # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
# )

# print("First 5 records:", df.head())

In [ ]:
#this is working

# Download latest version
# path = kagglehub.dataset_download("computingvictor/transactions-fraud-datasets")

# print("Path to dataset files:", path)

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

In [2]:
import pandas as pd
#df = pd.read_csv ('/home/coder/data/1/transactions_data.csv', nrows=100000)

In [3]:
import os

In [3]:
path ='/home/coder/data/1'
os.listdir('/home/coder/data/1')

['users_data.csv',
 'mcc_codes.json',
 'cards_data.csv',
 'transactions_data.csv',
 'train_fraud_labels.json']

In [4]:


mcc_codes = pd.read_json(
    os.path.join(path, "mcc_codes.json"),
    orient="index"
)

mcc_codes.reset_index(inplace=True)
mcc_codes.columns = ["mcc_code", "description"]

print(mcc_codes.head())

   mcc_code                           description
0      5812         Eating Places and Restaurants
1      5541                      Service Stations
2      7996  Amusement Parks, Carnivals, Circuses
3      5411          Grocery Stores, Supermarkets
4      4784                 Tolls and Bridge Fees

In [15]:
users_data= pd.read_csv(os.path.join(path, 'users_data.csv'))

In [16]:
cards_data = pd.read_csv(os.path.join(path, 'cards_data.csv'))

In [5]:
transactions_data = pd.read_csv(os.path.join(path, 'transactions_data.csv'), nrows=100000)
#train_fraud_labels = pd.read(os.path.join(path, 'train_fraud_labels'))

In [6]:
temp  = pd.read_json(os.path.join(path, 'train_fraud_labels.json'))
temp.shape

(8914963, 1)

In [9]:
temp.reset_index(inplace = True)

In [10]:
temp.columns

Index(['index', 'target'], dtype='object')

In [11]:
#temp = temp.reset_index()
temp = temp.rename(columns={'index':'id'})
transactions_data = transactions_data.merge (temp, on  = 'id', how ='left')

In [12]:
transactions_data.to_csv (os.path.join(path, 'transactions_target_data.csv'), index  =False)

In [13]:
del temp

## Add user data

In [17]:
users_data.head(2)

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,$37891,$77254,$191349,701,5

In [18]:
transactions_data.head(2)

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors,target
0,7475327,2010-01-01 00:01:00,1556,2972,$-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN,No
1,7475328,2010-01-01 00:02:00,561,4575,$14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,NaN,No

In [19]:
users_data = users_data.rename(columns = {'id': 'client_id'})

In [20]:
transactions_data1  = transactions_data.merge(users_data, left_on ='client_id', right_on='client_id', validate ='m:1' )

In [21]:
transactions_data1.shape[1]-transactions_data.shape[1]-users_data.shape[1]

-1

In [22]:
'client_id' in transactions_data1.columns

True

In [23]:
transactions_data1.columns

Index(['id', 'date', 'client_id', 'card_id', 'amount', 'use_chip',
       'merchant_id', 'merchant_city', 'merchant_state', 'zip', 'mcc',
       'errors', 'target', 'current_age', 'retirement_age', 'birth_year',
       'birth_month', 'gender', 'address', 'latitude', 'longitude',
       'per_capita_income', 'yearly_income', 'total_debt', 'credit_score',
       'num_credit_cards'],
      dtype='object')

In [24]:
#transactions_data1.mcc.value_counts(dropna = False)

In [25]:
cards_data.head(2)

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,09/2002,2008,No
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,04/2014,2014,No

In [26]:
cards_data.card_number.nunique(), cards_data.shape

(6146, (6146, 13))

In [27]:
transactions_data.head(1)

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors,target
0,7475327,2010-01-01 00:01:00,1556,2972,$-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN,No

## Add cards data

In [28]:
cards_data = cards_data.rename(columns={'id':'card_id'})

In [29]:
cards_data = cards_data.drop('client_id', axis = 1)

In [30]:
transactions_data2  = transactions_data1.merge(cards_data, left_on ='card_id', right_on='card_id', validate ='m:1' )

In [31]:
transactions_data2.shape[1]-transactions_data1.shape[1]-cards_data.shape[1]

-1

In [32]:
transactions_data2.columns

Index(['id', 'date', 'client_id', 'card_id', 'amount', 'use_chip',
       'merchant_id', 'merchant_city', 'merchant_state', 'zip', 'mcc',
       'errors', 'target', 'current_age', 'retirement_age', 'birth_year',
       'birth_month', 'gender', 'address', 'latitude', 'longitude',
       'per_capita_income', 'yearly_income', 'total_debt', 'credit_score',
       'num_credit_cards', 'card_brand', 'card_type', 'card_number', 'expires',
       'cvv', 'has_chip', 'num_cards_issued', 'credit_limit', 'acct_open_date',
       'year_pin_last_changed', 'card_on_dark_web'],
      dtype='object')

In [34]:
transactions_data2.target.value_counts(dropna=False)

target
No     67124
NaN    32769
Yes      107
Name: count, dtype: int64

In [ ]:
#transactions_data2.target=transactions_data3.target.fillna('No')

In [35]:
transactions_data2.to_csv (os.path.join(path, 'transactions_final__data.csv'), index  =False)

In [36]:
transactions_data2.to_csv ('/home/coder/agent-bootcamp/tests/tool_tests/example_files/data.csv', index  =False)

In [4]:
transactions_data2 = pd.read_csv('/home/coder/agent-bootcamp/tests/tool_tests/example_files/data.csv')

In [5]:
bad = transactions_data2[transactions_data2.target=='Yes']
print (bad.shape)
good = transactions_data2[transactions_data2.target=='No']
print (good.shape)

(107, 37)
(67124, 37)

In [7]:
transactions_data3  = pd.concat ([bad, good.sample (10000)], axis =0)

In [8]:
transactions_data3.shape

(10107, 37)

In [9]:
transactions_data3.to_csv ('/home/coder/agent-bootcamp/tests/tool_tests/example_files/data_b.csv', index  =False)

In [10]:
transactions_data3.target.value_counts(dropna=False)

target
No     10000
Yes      107
Name: count, dtype: int64

In [ ]:
transactions_data3.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,...,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
3459,7479444,2010-01-01 23:56:00,126,5497,$0.19,Online Transaction,90999,ONLINE,NaN,NaN,...,Debit,5110177937842500,04/2023,932,YES,1,$13555,11/2007,2011,No
9526,7486725,2010-01-03 20:58:00,126,5497,$339.00,Online Transaction,3558,ONLINE,NaN,NaN,...,Debit,5110177937842500,04/2023,932,YES,1,$13555,11/2007,2011,No
12989,7490901,2010-01-04 23:30:00,720,4136,$4.45,Online Transaction,24504,ONLINE,NaN,NaN,...,Debit,5549447642972376,08/2021,647,YES,1,$974,08/2004,2008,No
13000,7490914,2010-01-04 23:48:00,720,4136,$7.19,Online Transaction,38602,ONLINE,NaN,NaN,...,Debit,5549447642972376,08/2021,647,YES,1,$974,08/2004,2008,No
13081,7491008,2010-01-05 02:34:00,1644,3444,$8.76,Online Transaction,21776,ONLINE,NaN,NaN,...,Credit,4715738219735937,07/2023,643,YES,1,$10900,06/2009,2009,No